baseURL = "https://buster.wiki/"
languageCode = "en-us"
theme = "buster"
title = "Buster's Wiki"
enableEmoji = true
enableInlineShortcodes = true
googleAnalytics = 'UA-103669606-4'
disqusShortname = 'buster-wiki'
logFile = '/tmp/hugo.log'

[params]
custom_css = ["css/vendor.css", "css/style.css", "css/buster.css"]
custom_js = ["js/vendor.min.js", "js/app.js"]

[taxonomies]
tag = "tags"
pile = "piles"
projects = "projects"
category = "categories"
influence = "influences"
