baseURL = "https://buster.wiki/"
languageCode = "en-us"
theme = "buster"
title = "Buster's Wiki"

enableEmoji = true
enableInlineShortcodes = true
sectionPagesMenu = "main"

googleAnalytics = 'UA-103669606-4'
disqusShortname = 'buster-wiki'
logFile = '/tmp/hugo.log'

[params]
custom_css = ["css/vendor.css", "css/style.css", "css/open-iconic-bootstrap.min.css", "css/buster.css"]
custom_js = ["js/vendor.min.js", "js/app.js"]

[taxonomies]
tag = "tags"
pile = "piles"
projects = "projects"
category = "categories"
influence = "influences"

[outputs]
home = ["HTML", "RSS", "Bonsai"]

# Bonsai.io config for elasticsearch
# https://docs.bonsai.io/docs/hugo

[outputFormats.Bonsai]
baseName = "bonsai"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.bonsai]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags", "influences", "piles", "projects"]
