baseURL = "https://buster-wiki.netlify.com/"
languageCode = "en-us"
theme = "ananke"
title = "Buster's Wiki"
[params]
custom_css = ["css/vendor.css", "css/style.css"]
custom_js = ["js/vendor.min.js", "js/app.js"]
