---
new_page_extension: md
auto_deploy: true
admin_path: forestry
webhook_url: 
sections:
- type: directory
  path: content/pieces
  label: Pieces
  create: all
  match: "**/*"
- type: directory
  path: content/piles
  label: Piles
  create: all
  match: "**/*"
- type: directory
  path: content/influences
  label: Influences
  create: all
  match: "**/*"
- type: directory
  path: content/projects
  label: Projects
  create: all
  match: "**/*"
- type: directory
  path: content/beliefs
  label: Beliefs
  create: all
  match: "**/*"
- type: directory
  path: content/me
  label: Me
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.52'
